Adds Kitchen to showcase
shuding/nextra pull request #1565
Opened 2023-02-27 12:24 UTC by YounesBessa

I replaced hop with kitchen because hop no longer uses nextra for their project

2023-02-27 12:28 UTC, AntoineKM requested changes

2023-02-27 12:28 UTC, AntoineKM commented on docs/pages/showcase.mdx
> -import hop from 'public/showcase/hop.jpeg'
Remove hop image from `public/showcase`

2023-02-27 12:34 UTC, AntoineKM approved these changes
It looks great thank you so much!

2023-02-27 12:56 UTC, jerembdn approved these changes

2023-02-28 15:20 UTC, B2o5T commented
Sorry, I don’t think we’ll include it, we can't include every project who uses nextra, only popular

2023-02-28 15:20 UTC, closed without merging