Fixed accessibility (WCAG 2.1 AA) issue with author and date for for post in light mode
shuding/nextra pull request #1903
Opened 2023-05-24 14:35 UTC by filiphuhta

**Why**
I found accessibility in the light mode for **author** and **date** fields on posts for the blog template.

**What**
Fixed accessibility issues for **author** and **date** on posts in the `meta.tsx` file.

2023-05-24 17:20 UTC, B2o5T requested changes
Please rebase

2023-05-25 06:01 UTC, filiphuhta commented
> Please rebase

Fixed :)

2023-05-25 11:24 UTC, B2o5T commented on packages/nextra-theme-blog/src/meta.tsx
> +    resolvedTheme === 'dark' ? 'nx-text-gray-400' : 'nx-text-gray-600'
```suggestion
    'dark:nx-text-gray-400 nx-text-gray-600'
```
Use dark modifier instead, also refactor your previous usages

2023-06-19 16:17 UTC, B2o5T approved these changes

2023-06-19 16:17 UTC, merged