Fix leaky styles
shuding/nextra pull request #2765
Opened 2024-03-05 22:51 UTC by drwpow

## Changes

Fixes #2764 by scoping conflicting global styles to a classname. Now this is scoped to Nextra internal elements, while letting user styles operate as-expected.

![CleanShot 2024-03-05 at 15 47 32](https://github.com/shuding/nextra/assets/1369770/42c5e1d3-e34b-4e81-8cb7-9a65fde4e3bc)

2024-03-05 22:51 UTC, drwpow commented on packages/nextra-theme-docs/css/styles.css
> -  @apply nx-rounded;
Removed this because this seemed to be already applied in other areas.

2024-03-05 22:52 UTC, drwpow commented on packages/nextra-theme-docs/css/styles.css
> -[tabindex]:not([tabindex='-1']) {
I couldn’t find any `input` elements that needed this, or `[tabindex]` elements in the codebase. I’m guessing these were just anticipatory styles?

All the `<a>`, `<summary>`, and `<button>` tags generated by Nextra got the `.next-focusable` class.

2024-03-06 14:19 UTC, dimaMachina requested changes
but now focus state in header/sidebar/toc is broken

Also, what do you think about approach in this PR? https://github.com/shuding/nextra/pull/2740

https://github.com/shuding/nextra/assets/7361780/169f7088-4adc-4aa0-bf39-23f882851427

2024-03-06 14:59 UTC, drwpow commented
> Also, what do you think about approach in this PR? https://github.com/shuding/nextra/pull/2740

I wouldn’t mind that PR landing as well; that’s actually unrelated to this fix. That PR as I understand it is more resolving the cascade among internal styles. My issue is I’m using Nextra to document a design system, so I want to avoid _any_ style overrides whatsoever, because then I’d have to ship Nextra-specific style overrides to everywhere the DS is used.

Scoping, and just having no global element styles, would be my preferred fix. And using `@layers` or not wouldn’t affect that. But good catch on the missing elements! Will update those if you are OK with this approach to the solution (and open to alternate methods too!)

2024-03-08 16:04 UTC, dimaMachina commented
@drwpow thank you, to be honest, I don't have time to maintain nextra v2 and v3 versions, I update v2 only for critical bugs to avoid fixing huge git conflicts

Could you point your PR to v3 branch and only fix git conflicts

I will take care of rest and will push my changes directly on your PR

2024-03-08 16:44 UTC, drwpow commented
> Could you point your PR to v3 branch and only fix git conflicts

Will do! Will just open up another PR to make it easy.

> @drwpow thank you, to be honest, I don't have time to maintain nextra v2 and v3 versions, I update v2 only for critical bugs to avoid fixing huge git conflicts

Totally understand! ❤️ Thanks for all your amazing work on nextra. Setting boundaries on open source maintenance is necessary, and I respect and understand completely. It’s a smart thing to do.

2024-03-08 16:58 UTC, dimaMachina commented
Thank you for your compliments and for your contributions to make it better

More excited to ship Nextra 4 in 2024 with app router support and server components 🙌

2024-03-08 17:22 UTC, drwpow commented
Superceded by #2755

2024-03-08 17:22 UTC, closed without merging