fix: Cut the navbar items when it's too long (#2785)
shuding/nextra pull request #2787
Opened 2024-03-14 13:07 UTC by RiverTwilight

This pull request addresses issue #2785, ensuring that when the navbar has many items or items with long names, the overflow is managed elegantly without pushing the logo out of view.

Previously, an overflow of menu items caused layout issues, leading to a cluttered and inaccessible navbar.

## Before

![image](https://github.com/shuding/nextra/assets/52880665/fb6f852e-ab0c-4466-aac2-e6c4b2974106)

## After

![Screenshot 2024-03-14 at 21 02 41](https://github.com/shuding/nextra/assets/52880665/3832b151-4bf1-484e-8751-05d148899a17)

It's important to note that for most configurations, the visual appearance of the navbar remains unchanged:

![Screenshot 2024-03-14 at 21 04 40](https://github.com/shuding/nextra/assets/52880665/e3ae7b74-b9dc-4051-9dab-2fcf7539ecc2)

2024-03-15 00:16 UTC, dimaMachina requested changes
now dropdown with `type: 'menu'` is hidden while opening

https://github.com/shuding/nextra/assets/7361780/c892a367-0c8c-4d50-a91e-dc1c9a82f1f5

2024-03-15 00:22 UTC, dimaMachina commented on packages/nextra-theme-docs/src/components/navbar.tsx
> +          <div className="nx-flex nx-flex-row-reverse">
seems like now all links are in reversed order

2024-03-15 08:38 UTC, RiverTwilight commented
@dimaMachina The problems you mentioned are addressed. Currently if the menu is too long the search bar will be pushed out of the viewport, and the whole page will be scrollable on x-axis, which it's the best workaround, I think.

![Screenshot 2024-03-15 at 16 35 18](https://github.com/shuding/nextra/assets/52880665/78681ef1-e762-45a4-8ce2-2c9dbdf6f1cf)

2024-03-16 13:41 UTC, arno-fukuda commented
> @dimaMachina The problems you mentioned are addressed. Currently if the menu is too long the search bar will be pushed out of the viewport, and the whole page will be scrollable on x-axis, which it's the best workaround, I think.
> 
> ![Screenshot 2024-03-15 at 16 35 18](https://private-user-images.githubusercontent.com/52880665/313121193-78681ef1-e762-45a4-8ce2-2c9dbdf6f1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTYxNTQsIm5iZiI6MTcxMDU5NTg1NCwicGF0aCI6Ii81Mjg4MDY2NS8zMTMxMjExOTMtNzg2ODFlZjEtZTc2Mi00NWE0LThjZTItMmM5ZGJkZjZmMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzMzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjNmY2I2NTE4MGE1ZTYwOGY0NDM5ZmNmNjMwNTIyMTdiMzFiODVkMDVmMWViYTc1NDM5NjY4ZGZjNzYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tO24T4MqB7LScGZ7SnJ9pZQ0Mkdi8fE2NJWb6oCkAHs)

I might be overcomplicating things but ideally I'd like to see the hamburger kick in as soon as the sum of the total navbar items width starts exceeding the current viewport width.

2024-03-16 14:47 UTC, dimaMachina commented
> > @dimaMachina The problems you mentioned are addressed. Currently if the menu is too long the search bar will be pushed out of the viewport, and the whole page will be scrollable on x-axis, which it's the best workaround, I think.
> > ![Screenshot 2024-03-15 at 16 35 18](https://private-user-images.githubusercontent.com/52880665/313121193-78681ef1-e762-45a4-8ce2-2c9dbdf6f1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTYxNTQsIm5iZiI6MTcxMDU5NTg1NCwicGF0aCI6Ii81Mjg4MDY2NS8zMTMxMjExOTMtNzg2ODFlZjEtZTc2Mi00NWE0LThjZTItMmM5ZGJkZjZmMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzMzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjNmY2I2NTE4MGE1ZTYwOGY0NDM5ZmNmNjMwNTIyMTdiMzFiODVkMDVmMWViYTc1NDM5NjY4ZGZjNzYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tO24T4MqB7LScGZ7SnJ9pZQ0Mkdi8fE2NJWb6oCkAHs)
> 
> I might be overcomplicating things but ideally I'd like to see the hamburger kick in as soon as the sum of the total navbar items width starts exceeding the current viewport width.
> 
> So if someone created 100 categories, it would immediately start off as hamburger menu, even on fullscreen.

this would be a perfect fix, not sure how to properly implement it, without overcomplicating things, any ideas are welcome

Also, I would accept the solution with `overflow: scroll` for nav links in navbar

2024-03-16 15:13 UTC, RiverTwilight commented
> > > @dimaMachina The problems you mentioned are addressed. Currently if the menu is too long the search bar will be pushed out of the viewport, and the whole page will be scrollable on x-axis, which it's the best workaround, I think.
> 
> > > ![Screenshot 2024-03-15 at 16 35 18](https://private-user-images.githubusercontent.com/52880665/313121193-78681ef1-e762-45a4-8ce2-2c9dbdf6f1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTYxNTQsIm5iZiI6MTcxMDU5NTg1NCwicGF0aCI6Ii81Mjg4MDY2NS8zMTMxMjExOTMtNzg2ODFlZjEtZTc2Mi00NWE0LThjZTItMmM5ZGJkZjZmMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzMzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjNmY2I2NTE4MGE1ZTYwOGY0NDM5ZmNmNjMwNTIyMTdiMzFiODVkMDVmMWViYTc1NDM5NjY4ZGZjNzYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tO24T4MqB7LScGZ7SnJ9pZQ0Mkdi8fE2NJWb6oCkAHs)
> 
> > 
> 
> > I might be overcomplicating things but ideally I'd like to see the hamburger kick in as soon as the sum of the total navbar items width starts exceeding the current viewport width.
> 
> > 
> 
> > So if someone created 100 categories, it would immediately start off as hamburger menu, even on fullscreen.
> 
> 
> 
> this would be a perfect fix, not sure how to properly implement it, without overcomplicating things, any ideas are welcome
> 
> 
> 
> Also, I would accept the solution with `overflow: scroll` for nav links in navbar

Yes. I've thought about this idea but this might need JS to intercept, which makes the Navbar heavier, since we need dynamically measure the width of the available size and the horizontal stack width. Whatever I'll give another shot soon. There is no native CSS workaround to do this as far as I know.

The `overflow` solution seems not working as this cut dropdown menu (even only `overflow-x` is set to "scroll").

2024-03-19 05:57 UTC, RiverTwilight commented
@dimaMachina Now it should be the expected behavior you want. If the items are too long it will be moved to sidebar, which's similar to mobile screen.

![Screenshot 2024-03-19 at 13 55 50](https://github.com/shuding/nextra/assets/52880665/d3ad4a50-52b8-41a2-94b2-c1a3ccde662f)

Since the sidebar & hamburger share the same content, it's oevrcomplicated to let the hamburger contain the nav items and sidebar remains unchanged under overflow context.

Feel free to drop any comment!

2024-04-01 01:36 UTC, arno-fukuda commented
> If the items are too long it will be moved to sidebar

I believe this won't work for pages that use raw or full layout theme which is often used for landing pages.
```
{
  "index": {
    "title": "Home",
    "theme": {
      "layout": "raw"
    }
  }
}
```

2024-10-05 09:40 UTC, dimaMachina commented
superseded by https://github.com/shuding/nextra/pull/3376

2024-10-05 09:40 UTC, closed without merging