add image zoom component
shuding/nextra pull request #3829
Opened 2024-12-19 09:41 UTC by jellli

## Add build-in component to zoom image
I'm not sure whether it is necessary (and how) to give users more configurability.

Closes: https://github.com/shuding/nextra/issues/2238

## What's being changed (if available, include any code snippets, screenshots, or gifs):
![CleanShot 2024-12-19 at 17 39 06](https://github.com/user-attachments/assets/180965d6-6537-41b4-b67f-71f2157d17d4)
![CleanShot 2024-12-19 at 17 37 15](https://github.com/user-attachments/assets/62e46efd-0fc7-41b1-9542-80c7ef9c2653)

## Check off the following:

- [x] I have reviewed my changes in staging, available via the **View
      deployment** link in this PR's timeline (this link will be available after
      opening the PR).

2024-12-19 10:13 UTC, jellli commented
@dimaMachina need some help with `patches` property of pnpm, I can't install deps because of the same reason with [this](https://github.com/shuding/nextra/actions/runs/12410097629/job/34645013265?pr=3829) unless i delete this line of package.json
```diff
  "pnpm": {
    "overrides": {
      "esbuild": "^0.24.0",
      "next": "15.1.0"
    },
    "patchedDependencies": {
--    "@changesets/assemble-release-plan@6.0.4": "patches/@changesets__assemble-release-plan.patch",
      "eslint-plugin-deprecation@3.0.0": "patches/eslint-plugin-deprecation.patch",
      "tsup@8.3.5": "patches/tsup@8.3.5.patch"
    }
  }
```

2024-12-19 14:15 UTC, dimaMachina approved these changes
thank you for your nice contribution! I will review

2024-12-19 16:06 UTC, dimaMachina commented on packages/nextra/styles/rmiz.css
> +  -moz-appearance: none;
```suggestion
```
will be added by lightningcss

2024-12-19 16:06 UTC, dimaMachina commented on packages/nextra/styles/rmiz.css
> +  background-color: rgba(255, 255, 255, 0);
```suggestion
  background-color: #fff;
```

2024-12-19 16:20 UTC, dimaMachina commented on packages/nextra/src/client/components/image-zoom.tsx
> +  children?: React.ReactNode
`<img>` doesn't have `children`, why we need it?

2024-12-19 16:25 UTC, dimaMachina commented on packages/nextra-theme-docs/css/styles.css
> +@import 'nextra/styles/rmiz.css';
```suggestion
@import 'nextra/styles/react-medium-image-zoom.css';
```
let's be more precise

2024-12-19 16:40 UTC, dimaMachina commented on packages/nextra/styles/react-medium-image-zoom.css
> +}
maybe just set it to `none`? as we do for twoslash styles? https://github.com/shuding/nextra/blob/ac70dfedfec29f3634a333a282ee94c1e0765cb5/packages/nextra/styles/code-block.css#L89-L94

2024-12-19 16:43 UTC, dimaMachina requested changes
https://github.com/user-attachments/assets/99a5a1b7-eb33-4d64-930b-9eb25d0565ad

need to fix images statically imported in cards

https://github.com/shuding/nextra/blob/ac70dfedfec29f3634a333a282ee94c1e0765cb5/docs/pages/showcase.mdx?plain=1#L12-L14

2024-12-19 17:06 UTC, dimaMachina commented
> @dimaMachina need some help with `patches` property of pnpm, I can't install deps because of the same reason with [this](https://github.com/shuding/nextra/actions/runs/12410097629/job/34645013265?pr=3829) unless i delete this line of package.json
> 
> ```diff
>   "pnpm": {
>     "overrides": {
>       "esbuild": "^0.24.0",
>       "next": "15.1.0"
>     },
>     "patchedDependencies": {
> --    "@changesets/assemble-release-plan@6.0.4": "patches/@changesets__assemble-release-plan.patch",
>       "eslint-plugin-deprecation@3.0.0": "patches/eslint-plugin-deprecation.patch",
>       "tsup@8.3.5": "patches/tsup@8.3.5.patch"
>     }
>   }
> ```

✅ fixed

> Screen.Recording.2024-12-20.at.00.41.51.mov 
> need to fix images statically imported in cards
> 
> https://github.com/shuding/nextra/blob/ac70dfedfec29f3634a333a282ee94c1e0765cb5/docs/pages/showcase.mdx?plain=1#L12-L14

✅ fixed

2024-12-19 17:18 UTC, dimaMachina commented
white flash on the dark theme should be fixed as well 

https://github.com/user-attachments/assets/461a9d1f-f647-4361-8587-611eaf723df3

2024-12-19 17:40 UTC, dimaMachina commented
> white flash on the dark theme should be fixed as well
> 
>  Screen.Recording.2024-12-20.at.01.16.38.mov

✅ fixed as well

2024-12-19 18:07 UTC, dimaMachina approved these changes
Ok, I took the initiative and fixed all found issues, this feature is ready to ship in the minor v3 version

Please add a changeset with `minor` version and update docs to describe this new behaviour in the https://nextra.site/docs/guide/image page
And also describe how to disable zoom globally


```js
import { Image } from 'nextra/components'

// ... override mdx components 
components: {
  img: Image
}
```

Thanks for contributing!

2024-12-20 02:22 UTC, jellli commented
> Ok, I took the initiative and fixed all found issues, this feature is ready to ship in the minor v3 version
> 
> Please add a changeset with `minor` version and update docs to describe this new behaviour in the https://nextra.site/docs/guide/image page And also describe how to disable zoom globally
> 
> ```js
> import { Image } from 'nextra/components'
> 
> // ... override mdx components 
> components: {
>   img: Image
> }
> ```
> 
> Thanks for contributing!

Whoa, thx for the review! 
Yes, I will add docs about these changes.

2024-12-20 04:38 UTC, dimaMachina commented on docs/pages/docs/guide/image.mdx
> +  // ...your other configurations
```suggestion
  // ... your other configurations
```

2024-12-20 04:38 UTC, dimaMachina approved these changes
thank you!

2024-12-20 04:38 UTC, merged